spring.application.name=tenantsalesomzet

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# ==============================
# Optional: JPA / Hibernate Settings
# ==============================
# Jika Anda menggunakan Spring Data JPA, bisa tambahkan:

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#server.error.include-stacktrace=never

# Waktu maksimum (ms) menunggu koneksi dari pool sebelum timeout
spring.datasource.hikari.connection-timeout=30000

# Waktu (ms) sebelum koneksi dianggap idle dan di?evict
spring.datasource.hikari.idle-timeout=600000

spring.main.log-startup-info=false

server.port=8082
server.address=0.0.0.0